version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
